ignore:
  - "client/app/app.go"
  - "cmd/ocfclient/*.go"
  - "cmd/ocfbridge/*.go"
  - "**/main.go"
  - "**/test/**/*.go"
  - "**/*.pb.go"
  - "**/*.pb.gw.go"
  - "**/*_test.go"
  - "**/*.js"
  - "**/*.py"
