ignore:
  - "bridge/test/**/*.go"
  - "client/app/app.go"
  - "cmd/bridge-device/*.go"
  - "cmd/ocfclient/*.go"
  - "test/**/*.go"
  - "**/main.go"
  - "**/*.pb.go"
  - "**/*.pb.gw.go"
  - "**/*_test.go"
  - "**/*.js"
  - "**/*.py"
