apis:
  coap:
    id: 8f596b43-29c0-4147-8b40-e99268ab30f7
    name: "my-bridge-example"
    externalAddresses:
      - "127.0.0.1:15683"
      - "[::1]:15683"
    maxMessageSize: 2097152
numGeneratedBridgedDevices: 100
numResourcesPerDevice: 256