# Run special builds that should be supported
name: Builds

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
  workflow_dispatch:

jobs:
  builds:
    strategy:
      fail-fast: false
      matrix:
        include:
          # test build of oldest supported go version
          - name: go1.23
            go-version: "~1.23"
    uses: ./.github/workflows/build-with-cfg.yml
    with:
      go-version: ${{ matrix.go-version }}
