# Run special builds that should be supported
name: Builds

on:
  pull_request:
  workflow_dispatch:

jobs:
  builds:
    strategy:
      fail-fast: false
      matrix:
        include:
          # test build of oldest supported go version
          - name: go1.20
            go-version: "~1.20"
    uses: ./.github/workflows/build-with-cfg.yml
    with:
      go-version: ${{ matrix.go-version }}
