# Run special builds that should be supported
name: Builds

on:
  pull_request:
  workflow_dispatch:

jobs:
  builds:
    strategy:
      fail-fast: false
      matrix:
        include:
          # required by coap-gateway-go1-18 in https://github.com/plgd-dev/hub/blob/main/.github/workflows/publishDockerImagesGhcr.yml
          - name: go1.18
            go-version: "~1.18"
    uses: ./.github/workflows/build-with-cfg.yml
    with:
      go-version: ${{ matrix.go-version }}
