name: Delete old ghcr images
on:
  schedule:
    - cron: "0 1 * * *" # every day at 1:00am
  workflow_dispatch:

jobs:
  ghcr-cleanup:
    if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
    name: Delete stale or untagged images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout local actions
        uses: actions/checkout@v4
      - name: Delete stale or untagged images (1)
        id: run-1
        continue-on-error: true
        uses: ./.github/actions/cleanup-stale
        with:
          token: ${{ secrets.GHCR_CLEANUP_PAT }}
      - name: Delete stale or untagged images (2)
        id: run-2
        if: ${{ steps.run-1.outcome == 'failure' }}
        with:
          token: ${{ secrets.GHCR_CLEANUP_PAT }}
          delay: 60
        continue-on-error: true
        uses: ./.github/actions/cleanup-stale
      - name: Delete stale or untagged images (3)
        if: ${{ steps.run-2.outcome == 'failure' }}
        uses: ./.github/actions/cleanup-stale
        with:
          token: ${{ secrets.GHCR_CLEANUP_PAT }}
          delay: 60
