name: Golangci-lint

# golangci-lint is a fast Go linters runner. It runs linters in parallel,
# uses caching, supports yaml config, has integrations with all major IDE and
# has dozens of linters included.
# see: https://github.com/golangci/golangci-lint-action

on:
  pull_request:
  workflow_dispatch:
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go 1.22+
        uses: actions/setup-go@v5
        with:
          go-version: "^1.22" # The Go version to download (if necessary) and use.
          check-latest: true
          cache: false

      - run: go version

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61 # switch to latest if development is unfreezed
          args: --timeout=5m
