name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  ci:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup kernel for multicast messages, increase read buffer to 8MB
        run: sudo sysctl -w net.core.rmem_max=8388608

      # Runs a single command using the runners shell
      - name: Run a test
        run: make test

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
      - name: Collect iotivity logs for devsim-net-host failed test
        if: ${{ failure() }}
        run: docker logs -t devsim-net-host && cat .tmp/devsim-net-host/0.log
      
      - name: Collect iotivity logs for devsim-net-bridge failed test
        if: ${{ failure() }}
        run: docker logs -t devsim-net-bridge && cat .tmp/devsim-net-bridge/0.log
        
      - name: Publish the coverage
        run: bash <(curl -s https://codecov.io/bash)
