# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Test

on:
  workflow_call:
    inputs:
      name:
        type: string
        required: true
      bridgetest-enabled:
        type: boolean
        required: false
        default: false
      coverage:
        type: boolean
        required: false
        default: false
      tag:
        type: string
        required: true
      test-args:
        type: string
        required: false
        default: ""
      unittest-enabled:
        type: boolean
        required: false
        default: false
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Shallow checkout
        uses: actions/checkout@v4

      - name: Set up Go 1.22+
        uses: actions/setup-go@v5
        with:
          go-version: "^1.22"
          check-latest: true

      - run: go version

      - name: Setup kernel for multicast messages, increase read buffer to 8MB
        run: sudo sysctl -w net.core.rmem_max=8388608

      - name: Run integration tests
        run: make test DEVSIM_IMAGE=${{ inputs.tag }} ${{ inputs.test-args }}

      - name: Collect iotivity logs for devsim-net-host failed test
        if: ${{ failure() }}
        run: docker logs -t devsim-net-host && cat .tmp/devsim-net-host/0.log

      # Run after integration tests, because they always clean-up the output directory
      - name: Run bridge tests
        if: ${{ inputs.bridgetest-enabled }}
        run: |
          make test-bridge

      - name: Run unit tests
        if: ${{ inputs.unittest-enabled }}
        run: |
          make unit-test

      - name: Get output file name
        if: ${{ inputs.coverage }}
        id: coverage
        run: |
          HASH=`echo "${{ inputs.name }}${{ inputs.test-args }}" | sha1sum | cut -f 1 -d ' '`
          echo "directory=${HASH}" >> $GITHUB_OUTPUT

      - name: Upload coverage data
        if: ${{ inputs.coverage }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.coverage.outputs.directory }}
          # match bridge.coverage.txt,  bridge.unit.coverage.txt, coverage.txt, pkg.unit.coverage.txt and schema.unit.coverage.txt
          path: .tmp/*coverage.txt
          include-hidden-files: true
          if-no-files-found: error
          retention-days: 1
